sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t okkiman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true okkiman/react-test npm test

after_success:
  - docker build -t okkiman/multi-client ./client
  - docker build -t okkiman/multi-nginx ./nginx
  - docker build -t okkiman/multi-server ./server
  - docker build -t okkiman/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push okkiman/multi-client
  - docker push okkiman/multi-nginx
  - docker push okkiman/multi-server
  - docker push okkiman/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'lars-multi-docker'
  env: 'Larsmultidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-281107313981'
  bucket_path: 'lars-multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY